(PKGS) Hide root user in group share to prevent removal - We ensure that at least one user remains in the shared group to avoid traceback
22 Feb 2024 10:00:52

PHP XMLRPC call: dyngroup.setvisibility_group ('7', '2')

Python Server traceback:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/mmc/agent.py", line 1723, in _putResult
    result = f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mmc/plugins/dyngroup/__init__.py", line 212, in setvisibility_group
    DyngroupDatabase().setvisibility_group(ctx, id, visibility)
  File "/usr/lib/python3/dist-packages/mmc/plugins/dyngroup/database.py", line 599, in setvisibility_group
    s.display_in_menu = visibility
builtins.AttributeError: 'NoneType' object has no attribute 'display_in_menu'

(cherry picked from commit 8f1532959f848a0acd2b25a5eb3e58b0a00e2b2c)